### ISSUE TITLE
404 /keycloak/partials/realm-identity-provider-spid.html

### ISSUE THREAD

**Issue by DevNull-00** [italia/spid-keycloak-provider#42]
Ho un'istanza di keycloak 15.0.0 su docker con volumi che montano questo provider sulla directory apposita (docker) /opt/jboss/keycloak/providers.

Il provider viene rilevato correttamente e l'estensione caricata:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/43378701/191040897-ce52c7be-1a67-4aac-83cc-e753d349176f.png">

Ma quando vado a selezionarlo il template restituisce 404 e keycloak rimanda ad una pagina di errore:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/43378701/191041334-b8442b08-a693-493e-a346-5fff0bddf3f3.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/43378701/191041535-8ed4f3e3-0d34-4655-bab4-0403155aaf09.png">

Questa è la configurazione corrente del servizio di keycloak nel mio docker-compose:
```
  keycloak:
    depends_on:
      - db
    image: quay.io/keycloak/keycloak:15.0.0
    command:
      - "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile=preview"
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PWD:-password}
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    ports:
      - "9393:8080"
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/providers:/opt/jboss/keycloak/providers
```
